stages:
  - build
  - deploy

build job:
  stage: build
  script:
   - echo "i m build ... "
   - hostname
   - echo $CI_COMMIT_SHA
   - echo $CI_REGISTRY_USER
   - echo $CI_REGISTRY
   - echo $CI_REGISTRY_PASSWORD
  tags:
   - mybuild

production job:
  stage: deploy
  tags:
    - prod
  script:
   - hostname
   - echo "I am prod..."
  
